apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: c40iw1k0q-python
  janus-idp.io/tekton: c40iw1k0q-python
  backstage.io/kubernetes-id: c40iw1k0q-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: c40iw1k0q-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
